### PR TITLE
Adapts tests to work without toggler

### PR DESCRIPTION
**Pull request by Jonas-WMDE**
Bug: T109455
Bug: T109457
Fixes: T109460
Change-Id: I3c62d98fa763d32a71df70d0e237f15796691960

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
The step in the steps definition and the element definition could also be removed.

**Comment by Jonas-WMDE** [comment]
Done!

**Comment by WMDE-Fisch** [comment]
now you can also remove the inputextender_toggler in the statement_module.rb  ;-]

**Comment by Jonas-WMDE** [comment]
Done!

**Comment by thiemowmde** [comment]
+2, but depends on https://gerrit.wikimedia.org/r/278034 and should not be merged before.

**Pull request merged**
