### PR TITLE
Check that label is in firstHeading

### PR DESCRIPTION
**Pull request by Benestar**
When https://gerrit.wikimedia.org/r/#/c/203681/ gets merged this
patch should be adapted as it reflects the changes made to the DOM.

The variable mw_first_heading has been removed from EntityPage as
there is no difference to first_heading anymore and it was unused
anyways.

Bug: T93534

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
should only be merged together with 
https://gerrit.wikimedia.org/r/#/c/203681/

looks good :+1:

**Comment by Benestar** [comment]
Patch got merged on gerrit, this should be merged as well

**Comment by WMDE-Fisch** [comment]
Not deployed on beta yet so I will wait until then. 

I'll check on an daily basis though.

**Comment by WMDE-Fisch** [comment]
due to caching I missed the new heading deployment -.-

**Pull request merged**
