### PR TITLE
refactored statments to wait for elements

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
refactored to use page object element instead of @browser.element
refactored to use when_visible / when_present

### CODE REVIEW

**Comment by zeljkofilipin** [comment]
:+1:

**Comment by thiemowmde** [comment]
I'm not sure if it's a good idea to rename "statement" things to "claim". As far as I know there is no claim view in our JavaScript UI, isn't it?

**Comment by WMDE-Fisch** [comment]
I used the "claim" term in some methods after talking to Henning about the topic. A "statement" consists of several things one of them being the "claim". We use "claim" in the features and the steps, so I found it useful to rename the accessors and use it there as well.

**Comment by WMDE-Fisch** [comment]
plz review & merge @thiemowmde

**Comment by thiemowmde** [comment]
There is a lot of stuff going on in this PR I don't fully understand. Can we please have a 10 minutes pair review session? I would love to understand more of this.

**Pull request merged**
