### PR TITLE
updated to mw selenium 1.3

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
& general gemfile update

cant update to 1.4 - we need to update the mediawiki_api-wikidata gem

    Bundler could not find compatible versions for gem "mediawiki_api":
    In Gemfile:
     mediawiki_api-wikidata (>= 0) x86-mingw32 depends on
       mediawiki_api (~> 0.2.0) x86-mingw32
     mediawiki_selenium (~> 1.4.0) ruby depends on
       mediawiki_api (0.4.1)

### CODE REVIEW

**Comment by thiemowmde** [comment]
+2?

**Comment by WMDE-Fisch** [comment]
+2! :-)

**Comment by JeroenDeDauw** [comment]
+2,

**Comment by WMDE-Fisch** [comment]
P.S.:
for the mediawiki_api gem update there is already an issue
https://phabricator.wikimedia.org/T106811

but for now lets use 1.3 at least

**Pull request merged**
