### PR TITLE
Require mediawiki_selenium 1.6.0

### PR DESCRIPTION
**Pull request by tobijat**
Fixes https://phabricator.wikimedia.org/T115109

Note: this requires a release of wikidata_api 0.2.0. See
https://github.com/wmde/WikidataApiGem/pull/8

### CODE REVIEW

**Comment by zeljkofilipin** [comment]
Did you forget to update Gemfile.lock by running `bundle install`?

**Comment by tobijat** [comment]
@that will not work yet, as wikidata_api gem 0.2 is not released yet. See https://github.com/wmde/WikidataApiGem/pull/8

**Comment by tobijat** [comment]
@zeljkofilipin @WMDE-Fisch 
new version of wikidata_api gem has been released. now we are able to update to mediawiki_selenium 1.6.0

**Comment by WMDE-Fisch** [comment]
@tobijat please run bundle update and upload the updated Gemfile.lock otherwise it does not work for me

**Comment by tobijat** [comment]
@WMDE-Fisch oh, I only id a bundle install. Now did a bundle update as well.. should work now.

**Comment by WMDE-Fisch** [comment]
all browsertests seem to run fine ( or at least none fails that didn't fail before )

nice work & thanks :-)

**Pull request merged**
