### PR TITLE
UI now accepts time

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
UI now accepts time ( although the backend side fails due to a bug )

see https://phabricator.wikimedia.org/T102930

### CODE REVIEW

**Comment by thiemowmde** [comment]
The fact that TimeValues with hour/minute/second precision are rejected during validation is not a "bug". This is totally intentional. The *missing feature* is that such values are not rejected during *parsing*.

**Comment by WMDE-Fisch** [comment]
Then I will delete this PR. The test will fail as long as this is still unfixed :-)

**Comment by thiemowmde** [comment]
It's fine to have a test that tests the current behaviour, so I'm fine with merging this if it does exactly that. I just wanted to make the different points of view clear.

**Comment by WMDE-Fisch** [comment]
I disagree the failing test should always hint to the buggy UI :-D - IMHO we should leave the test like it is. Lets poke @tobijat for a comment.

**Comment by thiemowmde** [comment]
I do not want to merge a *failing* test (I haven't run this), but it's fine to test the current behaviour, even if it's already considered bogus.

**Pull request closed without merging**
