### PR TITLE
Add rubygems to env.rb

### PR DESCRIPTION
**Pull request by thiemowmde**
I constantly run into failures recently:
```
cannot load such file -- watir-webdriver/locators/element_locator (LoadError)
/var/lib/gems/1.9.1/gems/watir-webdriver-0.9.0/lib/watir-webdriver.rb:13:in `require'
/var/lib/gems/1.9.1/gems/watir-webdriver-0.9.0/lib/watir-webdriver.rb:13:in `<top (required)>'
/var/lib/gems/1.9.1/gems/mediawiki_selenium-1.3.0/lib/mediawiki_selenium/support/env.rb:4:in `require'
/var/lib/gems/1.9.1/gems/mediawiki_selenium-1.3.0/lib/mediawiki_selenium/support/env.rb:4:in `<top (required)>'
/var/lib/gems/1.9.1/gems/mediawiki_selenium-1.3.0/lib/mediawiki_selenium/support.rb:1:in `require'
/var/lib/gems/1.9.1/gems/mediawiki_selenium-1.3.0/lib/mediawiki_selenium/support.rb:1:in `<top (required)>'
/var/www/mediawiki/core/extensions/WikidataBrowserTests/tests/browser/features/support/env.rb:13:in `require'
/var/www/mediawiki/core/extensions/WikidataBrowserTests/tests/browser/features/support/env.rb:13:in `<top (required)>'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `each'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:42:in `run!'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in `execute!'
/var/lib/gems/1.9.1/gems/cucumber-1.3.20/bin/cucumber:13:in `<top (required)>'
/usr/local/bin/cucumber:19:in `load'
/usr/local/bin/cucumber:19:in `<main>'
```
This line fixed it. I'm not sure if it should be in the master repository.

Pinging @WMDE-Fisch.

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
Strange master works fine for me.
```
/var/lib/gems/1.9.1/gems/mediawiki_selenium-1.3.0/lib/mediawiki_selenium/support/env.rb:4:in `require'
```
Why is it mediawiki_selenium-1.3.0 ? the current master should use mediawiki_selenium-1.5.0
have you run bundle install after pulling the newest version?  :-)

**Comment by thiemowmde** [comment]
I did exactly what the [README](https://github.com/wmde/WikidataBrowserTests/blob/master/README.md) describes. To what does "pull new version" refer to?

**Comment by WMDE-Fisch** [comment]
You mean we should add "git pull" to the readme? Or did you do that already an still get these errors?

**Comment by thiemowmde** [comment]
I pulled this repository again and got the new lock file. Now it was `Installing mediawiki_selenium (1.5.0)` and the error message above is gone, even without the added "rubygems". But I can not tell if this is now an effect of me installing "rubygems" before. Is there a way to uninstall it, so I can try again?

**Comment by thiemowmde** [comment]
Still confusing. How is it possible that my environment stops working with that weird error message out of nowhere? It should still run with an older version of the repository. When and how was it possible to turn into an unusable state?

**Comment by WMDE-Fisch** [comment]
Actually the Readme is faulty ... that could be the reason ... normally you should only run `bundle install` not `bundle update`. The first one respects the `Gemfile.lock` settings. So you should not run into errors when it is configured correctly. 

You could checkout an older revision only running bundle install and it should work.

**Pull request closed without merging**
